import type { ScenarioDefinition } from "./types";

export const citetherScenario = {
  clockStart: "08:00",
  households: [
    {
      id: "hero_household",
      name: "The citEther household",
      homeLocationId: "home",
      solarGeneratedKwh: 19.5,
      homeSelfUseKwh: 7.1,
    },
  ],
  locations: [
    { id: "home", name: "Home", kind: "home", position: [-18, 0, -7], retailPriceKey: "home" },
    { id: "mums_flat", name: "Mum's flat", kind: "residential", position: [-12, 0, 1], retailPriceKey: "mums_flat" },
    { id: "job_site", name: "Tradie job site", kind: "job", position: [-3, 0, -12], retailPriceKey: "job_site" },
    { id: "ev_coast", name: "EV coast charger", kind: "transport", position: [20, 0, 14], retailPriceKey: "ev_coast" },
    { id: "hospital", name: "Hospital constrained node", kind: "hospital", position: [13, 0, -9], retailPriceKey: "hospital" },
    { id: "pod", name: "Community Pod", kind: "community", position: [-10, 0, 10], retailPriceKey: "pod" },
    { id: "charity", name: "Food bank", kind: "charity", position: [1, 0, 11], retailPriceKey: "charity" },
    { id: "business", name: "Local business", kind: "business", position: [6, 0, 2], retailPriceKey: "business" },
    { id: "grid", name: "Wholesale grid", kind: "grid", position: [23.5, 0, -4], retailPriceKey: "grid" },
  ],
  assets: [
    { id: "home_solar", locationId: "home", kind: "solar", capacityKwh: 19.5 },
    { id: "home_battery", locationId: "home", kind: "battery", capacityKwh: 10, initialKwh: 10 },
    { id: "home_meter", locationId: "home", kind: "meter" },
    { id: "job_generator", locationId: "job_site", kind: "generator" },
    { id: "coast_ev", locationId: "ev_coast", kind: "ev", capacityKwh: 68, initialKwh: 20 },
    { id: "coast_charger", locationId: "ev_coast", kind: "charger" },
    { id: "nurse_ev", locationId: "hospital", kind: "ev", capacityKwh: 72, initialKwh: 64 },
    { id: "pod_battery", locationId: "pod", kind: "battery", capacityKwh: 40, initialKwh: 14 },
  ],
  prices: {
    feedInTariff: 0.03,
    retailByLocation: {
      home: 0.31,
      mums_flat: 0.34,
      job_site: 0.95,
      ev_coast: 0.78,
      hospital: 1.2,
      pod: 0.3,
      charity: 0.31,
      business: 0.42,
      grid: 0.12,
    },
    wholesale: 0.12,
    fastChargerRate: 0.78,
  },
  networkFeePerKwh: 0.08,
  citetherMarginPct: 0.1,
  destinations: [
    { id: "mum_share", locationId: "mums_flat", kind: "share", priority: 1, networkFeeMultiplier: 1 },
    { id: "job_use", locationId: "job_site", kind: "use", priority: 2, networkFeeMultiplier: 1 },
    { id: "coast_use", locationId: "ev_coast", kind: "use", priority: 3, networkFeeMultiplier: 1 },
    { id: "charity_donate", locationId: "charity", kind: "donate", priority: 4, networkFeeMultiplier: 1 },
    { id: "business_sell", locationId: "business", kind: "sellBusiness", priority: 5, networkFeeMultiplier: 1 },
    { id: "pod_sell", locationId: "pod", kind: "sellPod", priority: 6, networkFeeMultiplier: 0.4 },
    { id: "grid_sell", locationId: "grid", kind: "sellGrid", priority: 7, networkFeeMultiplier: 0.5 },
    { id: "hospital_support", locationId: "hospital", kind: "support", priority: 8, networkFeeMultiplier: 1 },
  ],
  settlementEventSeeds: [
    {
      id: "mum_bill_offset",
      t: "09:20",
      beatId: 7,
      fromLocationId: "home",
      toLocationId: "mums_flat",
      destinationId: "mum_share",
      kwh: 2,
      labelTemplate: "Mum's flat bill offset",
    },
    {
      id: "tradie_diesel_avoided",
      t: "10:10",
      beatId: 8,
      fromLocationId: "home",
      toLocationId: "job_site",
      destinationId: "job_use",
      kwh: 2.8,
      labelTemplate: "Tradie site diesel avoided",
      carbonMode: "dieselAvoided",
    },
    {
      id: "coast_fast_charge",
      t: "12:45",
      beatId: 9,
      fromLocationId: "home",
      toLocationId: "ev_coast",
      destinationId: "coast_use",
      kwh: 2,
      labelTemplate: "Coast fast-charge offset",
    },
    {
      id: "hospital_grid_support",
      t: "18:00",
      beatId: 10,
      fromLocationId: "hospital",
      toLocationId: "hospital",
      destinationId: "hospital_support",
      kwh: 52,
      labelTemplate: "Hospital support earned",
    },
    {
      id: "food_bank_donation",
      t: "18:20",
      beatId: 11,
      fromLocationId: "home",
      toLocationId: "charity",
      destinationId: "charity_donate",
      kwh: 0.8,
      labelTemplate: "Food bank freezer credit donated",
    },
    {
      id: "business_local_sale",
      t: "18:25",
      beatId: 11,
      fromLocationId: "home",
      toLocationId: "business",
      destinationId: "business_sell",
      kwh: 1.1,
      labelTemplate: "Local business credit sold",
    },
    {
      id: "grid_fallback_sale",
      t: "18:30",
      beatId: 11,
      fromLocationId: "home",
      toLocationId: "grid",
      destinationId: "grid_sell",
      kwh: 0.5,
      labelTemplate: "Wholesale fallback settled",
    },
    {
      id: "pod_local_loop",
      t: "18:40",
      beatId: 12,
      fromLocationId: "home",
      toLocationId: "pod",
      destinationId: "pod_sell",
      kwh: 3.2,
      labelTemplate: "Community Pod local-loop settled",
    },
  ],
  carbon: {
    dieselKgPerKwh: 0.82,
    gridKgPerKwh: 0.12,
  },
} as const satisfies ScenarioDefinition;
